/**
 * Typed demo payloads for market / live / weekly pages when the API is down.
 * Same contract as dashboard MOCK_PICKS — live fetch always runs first.
 */
import type {
  CornerAggregatorPick,
  CornerCatalystPick,
  CornerPsychologyPick,
  CornerStage1Pick,
  CornerStage2Pick,
  DrawPick,
  DrawResponse,
  FHVIPick,
  GGCrossVerifyPick,
  GGForensicPick,
  GGO15Pick,
  GGPrecisionPick,
  GGPrecisionResponse,
  GGPsychologyPick,
  GGSupremePick,
  LiveAggregatorReport,
  LiveAlertPick,
  LiveDangerReport,
  LiveDashboardResult,
  LiveIncomingPick,
  LiveOrchestratorBoard,
  LivePrematchAudit,
  LivePrematchPick,
  LiveValidationBoard,
  LiveValidationPick,
  Over15ApexPick,
  Over15PsychologyPick,
  Over15Stage3Pick,
  Over25ApexPick,
  Over25ForecastPick,
  Over25GoldPick,
  Over25PsychologyPick,
  Over25Stage1Pick,
  Over25Stage2Pick,
  Over25Stage3Pick,
  SH8GoalPick,
  SHGGWinnerPick,
  SHMasterPick,
  SHVIPick,
  SOTPick,
  UnderdogApexPick,
  UnderdogBasePick,
  UnderdogMasterPick,
  UndersPick,
  UndersResponse,
  WinApexPick,
  WinForecastPick,
  WinPsychologyPick,
  WinRawPick,
  WinU2SPick,
  DnaProfile,
} from "@/lib/api";

// ── Win ───────────────────────────────────────────────────────────────────────

export const MOCK_WIN_APEX: WinApexPick[] = [
  {
    fixture_id: "demo-w1",
    Fixture: "Real Madrid vs Alaves",
    Target: "Home",
    Category: "Category 1",
    Cat_Priority: 1,
    Monte_Win_Prob: 81.6,
    Monte_Draw_Prob: 12.4,
    Lambda_Detail: "1.9 / 0.7",
    Underdog_Risk: "Low",
    Psych_Score: 88,
    Psych_Logic: "Venue dominance + chokehold midfield",
    Chokehold_Status: "Active",
    Veto_Reason: "None",
  },
  {
    fixture_id: "demo-w2",
    Fixture: "Liverpool vs Burnley",
    Target: "Home",
    Category: "Category 1",
    Cat_Priority: 1,
    Monte_Win_Prob: 79.2,
    Monte_Draw_Prob: 14.1,
    Lambda_Detail: "2.1 / 0.6",
    Underdog_Risk: "Low",
    Psych_Score: 85,
    Psych_Logic: "Anfield press intensity",
    Chokehold_Status: "Active",
    Veto_Reason: "None",
  },
  {
    fixture_id: "demo-w3",
    Fixture: "Bayer Leverkusen vs Augsburg",
    Target: "Home",
    Category: "Category 2",
    Cat_Priority: 2,
    Monte_Win_Prob: 72.4,
    Monte_Draw_Prob: 17.8,
    Lambda_Detail: "1.8 / 0.9",
    Underdog_Risk: "Medium",
    Psych_Score: 74,
    Psych_Logic: "High xG home script",
    Chokehold_Status: "Soft",
    Veto_Reason: "None",
  },
];

export const MOCK_DNA: DnaProfile[] = [
  {
    team_id: "83",
    team_name: "Real Madrid",
    Archetype: "Dominant Controller",
    Market_Power_Scores: {
      Corner_Power: 78.4,
      Goal_Intent: 91.2,
      BTTS_Friction: 42.1,
      Win_Dominance: 88.6,
    },
    Tactical_DNA: {
      Tempo: 72,
      Line_Height: "High",
      Risk_Appetite: "Aggressive",
      Verticality: "Mixed",
    },
    Raw_Audit_Metrics: {
      Avg_Corners: 6.4,
      Estimated_Crosses: 18.2,
      Estimated_Blocks: 9.1,
      Dangerous_Attacks: 54.3,
      Passing_Control: 62.8,
    },
  },
  {
    team_id: "14",
    team_name: "Liverpool",
    Archetype: "High-Press Hunter",
    Market_Power_Scores: {
      Corner_Power: 81.0,
      Goal_Intent: 89.5,
      BTTS_Friction: 48.6,
      Win_Dominance: 86.1,
    },
    Tactical_DNA: {
      Tempo: 84,
      Line_Height: "Very High",
      Risk_Appetite: "Aggressive",
      Verticality: "Vertical",
    },
    Raw_Audit_Metrics: {
      Avg_Corners: 7.1,
      Estimated_Crosses: 16.8,
      Estimated_Blocks: 8.4,
      Dangerous_Attacks: 58.9,
      Passing_Control: 58.2,
    },
  },
  {
    team_id: "9",
    team_name: "Manchester City",
    Archetype: "Possession Siege",
    Market_Power_Scores: {
      Corner_Power: 74.2,
      Goal_Intent: 93.8,
      BTTS_Friction: 38.4,
      Win_Dominance: 90.2,
    },
    Tactical_DNA: {
      Tempo: 68,
      Line_Height: "High",
      Risk_Appetite: "Controlled",
      Verticality: "Patient",
    },
    Raw_Audit_Metrics: {
      Avg_Corners: 6.9,
      Estimated_Crosses: 14.5,
      Estimated_Blocks: 7.2,
      Dangerous_Attacks: 61.4,
      Passing_Control: 71.5,
    },
  },
  {
    team_id: "18",
    team_name: "Alaves",
    Archetype: "Low-Block Defender",
    Market_Power_Scores: {
      Corner_Power: 41.2,
      Goal_Intent: 34.6,
      BTTS_Friction: 71.8,
      Win_Dominance: 28.4,
    },
    Tactical_DNA: {
      Tempo: 44,
      Line_Height: "Low",
      Risk_Appetite: "Conservative",
      Verticality: "Direct",
    },
    Raw_Audit_Metrics: {
      Avg_Corners: 3.8,
      Estimated_Crosses: 11.2,
      Estimated_Blocks: 14.6,
      Dangerous_Attacks: 28.1,
      Passing_Control: 39.4,
    },
  },
];

export const MOCK_WIN_PSYCH: WinPsychologyPick[] = [
  {
    Fixture: "Inter vs Salernitana",
    Master_Pick: "Home",
    Master_Prob: "76.3%",
    Audit_Score: 82,
    H_Base: 1.8,
    A_Base: 0.6,
    Tier: "Category 1",
    Spears: "Home attack",
    H_Quality: "High",
    A_Quality: "Low",
    Home_Logic: "Form W4/5",
    Away_Logic: "Fragile away",
  },
];

export const MOCK_WIN_U2S: WinU2SPick[] = [
  {
    Fixture: "Brighton vs Fulham",
    Underdog: "Fulham",
    Audit_Verdict: "PASS",
    Spear_Matchup: "Dog attack vs Fav def",
    Dog_Venue_SOT: 4.2,
    Fav_Venue_SOT: 3.1,
    Dog_H2H_SOT: 3.8,
    Fav_H2H_SOT: 2.9,
    Dog_Opp_Avg_Conceded: 1.4,
    Fav_Opp_Avg_Conceded: 0.9,
    Dog_Scoring_Consistency: "Solid",
    Psych_Score: 71,
    Tier: "Rank 1",
    Triggers: "Hot dog + venue SOT edge",
  },
  {
    Fixture: "Wolves vs Crystal Palace",
    Underdog: "Wolves",
    Audit_Verdict: "PASS",
    Spear_Matchup: "Dog set-piece threat",
    Dog_Venue_SOT: 3.9,
    Fav_Venue_SOT: 3.4,
    Dog_H2H_SOT: 3.5,
    Fav_H2H_SOT: 3.2,
    Dog_Opp_Avg_Conceded: 1.3,
    Fav_Opp_Avg_Conceded: 1.1,
    Dog_Scoring_Consistency: "Steady",
    Psych_Score: 66,
    Tier: "Rank 2",
    Triggers: "Due goal window",
  },
];

export const MOCK_WIN_FORECAST: WinForecastPick[] = [
  {
    fixture_id: "demo-wf1",
    fixture: "PSG vs Le Havre",
    side: "home",
    team_name: "PSG",
    win_odds: 1.35,
    poisson_win_prob: "67.9%",
    poisson_draw_prob: "18.2%",
    last_5_wins_overall: 4,
    last_5_wins_at_venue: 4,
    last_5_goals_scored: 11,
    opp_last_5_goals_scored: 3,
    opp_last_5_losses: 3,
    opp_last_5_conceded_raw: 9,
    opp_no_clean_sheet_count: 4,
    h2h_wins_last_5: 3,
    last_3_no_draw_BOTH: true,
    parity_score: 14,
    parity_even_count: 1,
  },
];

export const MOCK_WIN_RAW: WinRawPick[] = [
  {
    fixture_id: "demo-wr1",
    fixture: "Benfica vs Porto",
    side: "home",
    team_name: "Benfica",
    win_odds: 2.1,
    last_5_wins_overall: 3,
    last_5_wins_at_venue: 3,
    last_5_goals_scored: 8,
    opp_last_5_goals_scored: 5,
    opp_last_5_losses: 2,
    opp_last_5_conceded_raw: 7,
    opp_no_clean_sheet_count: 3,
    h2h_wins_last_5: 2,
    last_3_no_draw_BOTH: false,
    parity_score: 6,
    parity_even_count: 2,
  },
];

// ── GG ────────────────────────────────────────────────────────────────────────

export const MOCK_GG_SUPREME: GGSupremePick[] = [
  {
    fixture_id: "demo-gg1",
    Fixture: "Man City vs Arsenal",
    Category: "Category 1",
    Cat_Priority: 1,
    Monte_GG_Prob: 78.4,
    NGG_Risk: 21.6,
    Base_Marks: "A",
    DNA_Status: "Aligned",
    Psych_Score: 84,
    Psych_Triggers: "H2H BTTS",
    VIP_Status: "VIP",
    Veto_Status: "None",
    Spears: "Both attack",
  },
];

export const MOCK_GG_FORENSICS: GGForensicPick[] = [
  {
    fixture_id: "demo-ggf1",
    league_id: "8",
    Fixture: "Bayern Munich vs Dortmund",
    Score: "74",
    DNA_Intelligence: "High",
    "Poisson%": 71.2,
    H2H_GG: "4/5",
    DNA_Insight: "Open scripts",
    Ranks: "1 / 3",
    Forensic_Audit: "PASS",
  },
];

export const MOCK_GG_PSYCH: GGPsychologyPick[] = [
  {
    Fixture: "Ajax vs PSV",
    MC_Rank: "1",
    MC_Prob: "68.5%",
    Psych_Score: 76,
    Spears: "Venue BTTS",
    Tier: "Category 2",
    Psych_Triggers: "GK liability",
  },
];

const MOCK_GG_PRECISION_ROW: GGPrecisionPick = {
  fixture_id: "demo-ggp1",
  fixture: "Man City vs Arsenal",
  home_team: "Man City",
  away_team: "Arsenal",
  league_id: "8",
  lambda_home: 1.7,
  lambda_away: 1.4,
  combined_lambda: 3.1,
  mc_btts_prob: 0.78,
  venue_btts_combined: 0.72,
  h2h_btts_rate: 0.8,
  home_gk_liable: true,
  away_gk_liable: true,
  home_gk_cpg: 1.42,
  away_gk_cpg: 1.28,
  home_gk_note: "Soft wall — 1.42 CPG L10",
  away_gk_note: "Elevated — shot volume spike",
  fatigue_home: 0.22,
  fatigue_away: 0.35,
  league_weight: 1.0,
  gg_score: 86,
  gg_signals_fired: 4,
  gg_tier: "Category 1",
  sig1_mc_btts: 1,
  sig2_venue_btts: 1,
  sig3_gk_vuln: 1,
  sig4_h2h_btts: 1,
  sig5_directional: 0,
};

const MOCK_GG_PRECISION_ROW_2: GGPrecisionPick = {
  fixture_id: "demo-ggp2",
  fixture: "Bayern Munich vs Stuttgart",
  home_team: "Bayern Munich",
  away_team: "Stuttgart",
  league_id: "82",
  lambda_home: 2.1,
  lambda_away: 1.3,
  combined_lambda: 3.4,
  mc_btts_prob: 0.74,
  venue_btts_combined: 0.69,
  h2h_btts_rate: 0.75,
  home_gk_liable: false,
  away_gk_liable: true,
  home_gk_cpg: 0.88,
  away_gk_cpg: 1.55,
  home_gk_note: "Solid wall",
  away_gk_note: "Fragile — high CPG away",
  fatigue_home: 0.18,
  fatigue_away: 0.41,
  league_weight: 1.05,
  gg_score: 81,
  gg_signals_fired: 4,
  gg_tier: "Category 1",
  sig1_mc_btts: 1,
  sig2_venue_btts: 1,
  sig3_gk_vuln: 1,
  sig4_h2h_btts: 1,
  sig5_directional: 0,
};

const MOCK_GG_PRECISION_ROW_3: GGPrecisionPick = {
  fixture_id: "demo-ggp3",
  fixture: "Inter vs Napoli",
  home_team: "Inter",
  away_team: "Napoli",
  league_id: "384",
  lambda_home: 1.5,
  lambda_away: 1.4,
  combined_lambda: 2.9,
  mc_btts_prob: 0.71,
  venue_btts_combined: 0.66,
  h2h_btts_rate: 0.7,
  home_gk_liable: true,
  away_gk_liable: true,
  home_gk_cpg: 1.15,
  away_gk_cpg: 1.19,
  home_gk_note: "Borderline liable",
  away_gk_note: "Borderline liable",
  fatigue_home: 0.28,
  fatigue_away: 0.31,
  league_weight: 0.98,
  gg_score: 77,
  gg_signals_fired: 3,
  gg_tier: "Category 2",
  sig1_mc_btts: 1,
  sig2_venue_btts: 1,
  sig3_gk_vuln: 1,
  sig4_h2h_btts: 0,
  sig5_directional: 0,
};

const MOCK_GG_O15_ROW: GGO15Pick = {
  fixture_id: "demo-o15p1",
  fixture: "Napoli vs Roma",
  home_team: "Napoli",
  away_team: "Roma",
  league_id: "384",
  o15_tier: "Tier 1",
  o15_score: 91,
  combined_lambda: 2.8,
  mc_over15_prob: 0.88,
  sig1_combined_lambda: 1,
  sig2_mc_over15: 1,
  sig3_venue_goals_avg: 1,
  sig4_league_weight: 1,
  sig5_fatigue_penalty: 0,
  combined_venue_goals_avg: 3.1,
  venue_goals_avg_home: 1.8,
  venue_goals_avg_away: 1.3,
  fatigue_home: 0.12,
  fatigue_away: 0.24,
};

const MOCK_GG_O15_ROW_2: GGO15Pick = {
  fixture_id: "demo-o15p2",
  fixture: "PSG vs Lyon",
  home_team: "PSG",
  away_team: "Lyon",
  league_id: "301",
  o15_tier: "Tier 1",
  o15_score: 88,
  combined_lambda: 3.0,
  mc_over15_prob: 0.86,
  sig1_combined_lambda: 1,
  sig2_mc_over15: 1,
  sig3_venue_goals_avg: 1,
  sig4_league_weight: 1,
  sig5_fatigue_penalty: 0,
  combined_venue_goals_avg: 3.4,
  venue_goals_avg_home: 2.1,
  venue_goals_avg_away: 1.3,
  fatigue_home: 0.19,
  fatigue_away: 0.33,
};

export const MOCK_GG_PRECISION: GGPrecisionResponse = {
  gg: [MOCK_GG_PRECISION_ROW, MOCK_GG_PRECISION_ROW_2, MOCK_GG_PRECISION_ROW_3],
  o15: [MOCK_GG_O15_ROW, MOCK_GG_O15_ROW_2],
};

export const MOCK_GG_CROSS: GGCrossVerifyPick[] = [
  {
    fixture_id: "demo-ggc1",
    home_team: "Man City",
    away_team: "Arsenal",
    league_id: "8",
    gg_prob_pct: 78.4,
    tier: "Category 1",
    verification_days: 7,
    table_distance: 2,
    audit_timestamp: "demo",
  },
];

// ── Over 2.5 / 1.5 ────────────────────────────────────────────────────────────

export const MOCK_O25_APEX: Over25ApexPick[] = [
  {
    fixture_id: "demo-o25a",
    Fixture: "Leverkusen vs Union Berlin",
    Category: "Category 1",
    Cat_Priority: 1,
    Super_Monte_Prob: 74.8,
    U25_Risk: 25.2,
    Base_Grade: "A",
    DNA_Status: "Aligned",
    Psych_Score: 80,
    Psych_Triggers: "Council pass + gold H2H",
    VIP_Status: "VIP",
    Veto_Status: "None",
  },
  {
    fixture_id: "demo-o25b",
    Fixture: "Ajax vs Feyenoord",
    Category: "Category 1",
    Cat_Priority: 1,
    Super_Monte_Prob: 71.2,
    U25_Risk: 28.8,
    Base_Grade: "A-",
    DNA_Status: "Open script",
    Psych_Score: 76,
    Psych_Triggers: "Both attack DNA",
    VIP_Status: "VIP",
    Veto_Status: "None",
  },
  {
    fixture_id: "demo-o25c",
    Fixture: "Celtic vs Rangers",
    Category: "Category 2",
    Cat_Priority: 2,
    Super_Monte_Prob: 68.5,
    U25_Risk: 31.5,
    Base_Grade: "B+",
    DNA_Status: "Volatile",
    Psych_Score: 70,
    Psych_Triggers: "Derby tempo spike",
    VIP_Status: "Watch",
    Veto_Status: "None",
  },
];

export const MOCK_O25_GOLD: Over25GoldPick[] = [
  {
    fixture_id: "demo-o25g",
    league: "Bundesliga",
    kickoff_datetime: "2026-07-17T15:00:00Z",
    teams: {
      home: { id: "1", name: "Leverkusen" },
      away: { id: "2", name: "Union Berlin" },
    },
    flags: {
      both_teams_high_attack: true,
      h2h_o15_100_percent: true,
      both_2h_goal_100_percent: false,
      home_h2h_win_100: false,
      away_h2h_win_100: false,
      h2h_gg_100: true,
      h2h_o25_100: true,
    },
    metrics: {
      home_goals_last_5: 12,
      away_goals_last_5: 8,
      h2h_matches_analyzed: 5,
    },
  },
];

export const MOCK_O25_FORECAST: Over25ForecastPick[] = [
  {
    fixture_id: "demo-o25f",
    league: "La Liga",
    fixture: "Atletico vs Sevilla",
    o25_odds: 1.85,
    kill_switch_pass: true,
    poisson_over_prob_num: 64.5,
    council_votes: "7/9",
    pos_gap: 4,
    parity_diff: 3,
    h2h_overs_last_5: 4,
    combined_gs_last_5: 18,
  },
];

export const MOCK_O25_PSYCH: Over25PsychologyPick[] = [
  {
    Fixture: "Benfica vs Porto",
    Base_Poisson: "62%",
    Base_Grade: "B+",
    Score: 71,
    Tier: "Category 2",
    Reasons: "H2H overs",
  },
];

export const MOCK_O25_S3: Over25Stage3Pick[] = [
  {
    Match: "Leverkusen vs Union Berlin",
    Odds: 1.72,
    "Poisson%": 74.8,
    Grade: "A",
    GradeNum: 4,
    H2H_Record: "4/5 O2.5",
    PickedBy: "Council",
    Failures: "",
  },
];

export const MOCK_O25_S2: Over25Stage2Pick[] = [
  {
    id: "demo-s2",
    fixture: "Atletico vs Sevilla",
    Time: "15:00",
    Votes: 7,
    Odds: 1.9,
    Algorithm: "Council",
    Reasons: "Attack stacks",
  },
];

export const MOCK_O25_S1: Over25Stage1Pick[] = [
  {
    id: "demo-s1",
    fixture: "Benfica vs Porto",
    Time: "18:00",
    Odds: 1.95,
    Confidence: "High",
    Algorithm: "Poisson",
  },
];

export const MOCK_O15_APEX: Over15ApexPick[] = [
  {
    Fixture: "Napoli vs Roma",
    Base_Poisson: "88%",
    Base_Grade: "A",
    Score: 91,
    Tier: "Tier 1",
    Reasons: "Unified GG/O1.5 head",
  },
];

export const MOCK_O15_PSYCH: Over15PsychologyPick[] = [
  {
    Fixture: "Marseille vs Lyon",
    Base_Poisson: "79%",
    Base_Grade: "A-",
    Score: 82,
    Tier: "Tier 2",
    Reasons: "Venue goals",
  },
];

export const MOCK_O15_S3: Over15Stage3Pick[] = [
  {
    Match: "Napoli vs Roma",
    Odds: 1.28,
    "Poisson%": 88.2,
    Grade: "A",
    GradeNum: 4,
    H2H_Record: "5/5 O1.5",
    PickedBy: "Apex",
    Failures: "",
  },
];

// ── Draw / Unders ─────────────────────────────────────────────────────────────

const MOCK_DRAW_ROW: DrawPick = {
  fixture_id: "demo-d1",
  fixture: "Juventus vs Milan",
  home_team: "Juventus",
  away_team: "Milan",
  tier: "Diamond Lock",
  section: "magnet",
  composite_draw_score: 79,
  mc_draw_prob: 0.342,
  poisson_draw_prob: 0.31,
  dmi: 0.82,
  parity: 0.95,
  draw_odds: 3.2,
  value_edge: 0.12,
  mc_spread: 0.04,
  mc_stability: "High",
  most_likely_draw_score: "1-1",
  most_likely_draw_pct: 18.5,
  home_draws: 3,
  away_draws: 2,
  h2h_draws: 2,
  total_draws: 7,
  fatigue_score: 0.4,
  home_position: 4,
  away_position: 5,
};

export const MOCK_DRAW: DrawResponse = {
  draws: [MOCK_DRAW_ROW],
  parity_list: [{ ...MOCK_DRAW_ROW, section: "parity" }],
  amateurs_list: [
    {
      ...MOCK_DRAW_ROW,
      fixture_id: "demo-d2",
      fixture: "Fenerbahce vs Galatasaray",
      home_team: "Fenerbahce",
      away_team: "Galatasaray",
      tier: "Fire Pick",
      section: "amateurs",
      mc_draw_prob: 0.298,
      total_draws: 8,
    },
  ],
};

const MOCK_UNDERS_ROW: UndersPick = {
  fixture_id: "demo-u1",
  fixture: "Getafe vs Cadiz",
  home_team: "Getafe",
  away_team: "Cadiz",
  combined_lambda: 1.9,
  mc_u25_prob: 0.715,
  mc_u35_prob: 0.82,
  u25_score: 68,
  u25_tier: "Solid Lean",
  u25_signals_fired: 4,
  u35_score: 74,
  u35_tier: "Solid Lean",
  home_gk_cpg: 0.82,
  away_gk_cpg: 0.91,
  home_gk_note: "Hard wall — low CPG",
  away_gk_note: "Stable wall",
  fatigue_home: 0.31,
  fatigue_away: 0.44,
};

const MOCK_UNDERS_ROW_2: UndersPick = {
  fixture_id: "demo-u2",
  fixture: "Burnley vs Everton",
  home_team: "Burnley",
  away_team: "Everton",
  combined_lambda: 2.05,
  mc_u25_prob: 0.682,
  mc_u35_prob: 0.79,
  u25_score: 64,
  u25_tier: "Solid Lean",
  u25_signals_fired: 3,
  u35_score: 71,
  u35_tier: "Solid Lean",
  home_gk_cpg: 0.95,
  away_gk_cpg: 1.02,
  home_gk_note: "Stable",
  away_gk_note: "Slight leak risk",
  fatigue_home: 0.27,
  fatigue_away: 0.38,
};

const MOCK_UNDERS_ROW_3: UndersPick = {
  fixture_id: "demo-u3",
  fixture: "Metz vs Clermont",
  home_team: "Metz",
  away_team: "Clermont",
  combined_lambda: 1.78,
  mc_u25_prob: 0.741,
  mc_u35_prob: 0.85,
  u25_score: 72,
  u25_tier: "Strong Lean",
  u25_signals_fired: 5,
  u35_score: 78,
  u35_tier: "Strong Lean",
  home_gk_cpg: 0.74,
  away_gk_cpg: 0.81,
  home_gk_note: "Elite wall",
  away_gk_note: "Hard wall",
  fatigue_home: 0.22,
  fatigue_away: 0.29,
};

export const MOCK_UNDERS: UndersResponse = {
  u25: [MOCK_UNDERS_ROW, MOCK_UNDERS_ROW_2, MOCK_UNDERS_ROW_3],
  u35: [
    { ...MOCK_UNDERS_ROW, fixture_id: "demo-u35-1" },
    { ...MOCK_UNDERS_ROW_2, fixture_id: "demo-u35-2" },
    { ...MOCK_UNDERS_ROW_3, fixture_id: "demo-u35-3", fixture: "Udinese vs Empoli" },
  ],
};

// ── Corners / SOT / FHVI / SHVI / Underdog ────────────────────────────────────

export const MOCK_CORNER_AGG: CornerAggregatorPick[] = [
  {
    Fixture: "Newcastle vs Aston Villa",
    Master_Score: 87,
    Chaos_Rating: 6.2,
    Tier: "Tier 1",
    True_Corner_Fav: "Home",
    Match_Flow: "Home pressure",
    "U2.5%": "42%",
    UD_Prob: "28%",
    NB_Prob: "55%",
    Total_Exp: 11.4,
    Home_Pos: 5,
    Away_Pos: 8,
    Friction: "High",
    Home_Wounded: "No",
    Home_Wound_Int: "—",
    Away_Wounded: "Yes",
    Away_Wound_Int: "Medium",
    Home_Team: "Newcastle",
    Away_Team: "Aston Villa",
    Home_Score: 52,
    Away_Score: 41,
    Home_Label: "Pressure",
    Away_Label: "Counter",
    Home_DNA: "High tempo",
    Away_DNA: "Compact",
    Home_SH_Ratio: 0.55,
    Away_SH_Ratio: 0.48,
  },
];

export const MOCK_CORNER_CAT: CornerCatalystPick[] = [
  {
    fixture_name: "Sevilla vs Villarreal",
    predicted_corners: 10.8,
    corner_tier: "Tier 2",
    home_position: 9,
    away_position: 6,
    friction_grade: "B",
    home_is_wounded_beast: false,
    home_wounded_intensity: "—",
    away_is_wounded_beast: true,
    away_wounded_intensity: "High",
  },
];

export const MOCK_CORNER_PSYCH: CornerPsychologyPick[] = [
  {
    fixture_name: "Newcastle vs Aston Villa",
    home_position: 5,
    away_position: 8,
    friction_grade: "A",
    standings_gap: 3,
    tactical_intelligence_grade: "A-",
    tactical_note: "Home wing pressure",
    is_wounded_beast: true,
    wounded_reason: "Table gap",
    wounded_team_name: "Aston Villa",
  },
];

export const MOCK_CORNER_S2: CornerStage2Pick[] = [
  {
    fixture_id: "demo-c2",
    fixture: "Sevilla vs Villarreal",
    stage1_predicted_corners: 10.2,
    stage2_predicted_corners: 10.8,
    expected_total_corners: 10.8,
    corner_tier: "Tier 2",
    style_alignment: "Aligned",
    expected_difference: 1.4,
    avg_confidence: 0.71,
    home_is_persistent_venue: true,
    away_is_persistent_venue: false,
    home_is_persistent_overall: true,
    away_is_persistent_overall: false,
  },
];

export const MOCK_CORNER_S1: CornerStage1Pick[] = [
  {
    fixture_id: "demo-c1",
    fixture: "Newcastle vs Aston Villa",
    expected_total_corners: 11.2,
    corner_tier: "Tier 1",
    expected_difference: 2.1,
    team_more_corners: "Home",
    team_more_corners_probability_like: 0.68,
    avg_confidence: 0.77,
    home_win_odds: 2.05,
    over_2_5_odds: 1.8,
    tier_1_priority: true,
  },
];

export const MOCK_SOT: SOTPick[] = [
  {
    Fixture: "Chelsea vs Brentford",
    Verdict: "💎 DIAMOND (Stable & High)",
    Proj_SOT: 10.8,
    "Poisson_Over_8.5": "78%",
    Consistency: "High",
    Game_Script: "Home control",
    Momentum: "Rising",
    "1x2_Home_Odd": 1.65,
  },
  {
    Fixture: "Tottenham vs Brighton",
    Verdict: "🔥 FIRE (High Volume)",
    Proj_SOT: 11.4,
    "Poisson_Over_8.5": "82%",
    Consistency: "Very High",
    Game_Script: "Open midfield",
    Momentum: "Surging",
    "1x2_Home_Odd": 1.95,
  },
  {
    Fixture: "Atalanta vs Fiorentina",
    Verdict: "Solid Lean",
    Proj_SOT: 9.6,
    "Poisson_Over_8.5": "71%",
    Consistency: "Medium-High",
    Game_Script: "Transition chaos",
    Momentum: "Stable",
    "1x2_Home_Odd": 2.05,
  },
];

export const MOCK_FHVI: FHVIPick[] = [
  {
    fixture: "Bologna vs Lazio",
    ht_score: "1-0",
    ft_score: "2-1",
    fhvi_score: 11,
    fhvi_label: "🔥 Very explosive FH",
    fh_pressure: 8.2,
    country: "Italy",
    comb_fh_r: 0.72,
    avg_sh_goals: 1.1,
    h_fh_r_disp: 0.7,
    a_fh_r_disp: 0.65,
    h_fh_c_r_disp: 0.4,
    a_fh_c_r_disp: 0.5,
    Category: "🔥 Very explosive FH",
  },
];

export const MOCK_SHVI: SHVIPick[] = [
  {
    fixture: "Feyenoord vs AZ Alkmaar",
    ht_score: "0-0",
    ft_score: "2-1",
    shvi_score: 12,
    shvi_label: "🔥 Very explosive SH",
    sh_pressure: 8.8,
    country: "Netherlands",
    comb_sh_r: 0.75,
    avg_fh_goals: 0.9,
    h_sh_r_disp: 0.78,
    a_sh_r_disp: 0.7,
    h_sh_c_r_disp: 0.45,
    a_sh_c_r_disp: 0.5,
    Category: "🔥 Very explosive SH",
  },
];

export const MOCK_SH_GG: SHGGWinnerPick[] = [
  {
    fixture_id: "demo-shgg",
    league: "La Liga",
    kickoff_datetime: "2026-07-17T17:00:00Z",
    teams: {
      home: { id: "10", name: "Atletico" },
      away: { id: "11", name: "Sevilla" },
    },
    pick_labels: ["2H GG"],
    flags: {
      both_2h_goal_100_percent: true,
      home_h2h_win_100: false,
      away_h2h_win_100: false,
      h2h_gg_100: true,
      h2h_o25_100: false,
    },
    metrics: {
      home_2h_rate: 0.8,
      away_2h_rate: 0.75,
      h2h_matches_analyzed: 5,
    },
  },
];

export const MOCK_SH_MASTER: SHMasterPick[] = [
  {
    fixture: "Atletico vs Sevilla",
    league: "La Liga",
    shvi_score: 11,
    sh_pressure: 8.1,
    ht: "0-0",
    ft: "1-1",
    sh_scoring_rate: "72%",
    avg_fh_goals: 0.8,
    late_threat: "HIGH",
  },
];

export const MOCK_SH_8GOAL: SH8GoalPick[] = [
  {
    Fixture_ID: "demo-sh8",
    League: "Eredivisie",
    Time: "15:30",
    Fixture: "Feyenoord vs AZ Alkmaar",
    H_Goals_L5: 9,
    A_Goals_L5: 8,
    Labels: "SH GG",
    Status: "LIVE",
  },
];

export const MOCK_UD_APEX: UnderdogApexPick[] = [
  {
    fixture_id: "demo-ud1",
    Fixture: "Brighton vs Fulham",
    Rank: "Rank 1",
    Monte_UD_Prob: "68.5%",
    Engine: "Apex",
    Handshake: "PASS",
    DNA: "Aligned",
    Rule: "Fav vuln",
    Fav_Vuln: "74%",
    SH_GG_Label: "Watch",
  },
];

export const MOCK_UD_AUDIT: UnderdogMasterPick[] = [
  {
    fixture_id: "demo-uda1",
    fixture: "Brighton vs Fulham",
    underdog_team: "Fulham",
    Audit_Real_Prob: "68%",
    Dog_Score_Prob: "62%",
    Fav_Spear_Power: "Medium",
    Dominance_Gap: 8,
    Audit_Verdict: "PASS",
    parity_gap: 6,
    dog_is_hot: true,
    dog_due_goal: true,
    fav_cs_streak: 0,
  },
];

export const MOCK_UD_BASE: UnderdogBasePick[] = [
  {
    fixture_id: "demo-udb1",
    fixture: "Valencia vs Alaves",
    league: "La Liga",
    underdog_team: "Alaves",
    dog_odds: 4.2,
    dog_score_prob: "54%",
    parity_gap: 9,
    dog_att_strength: 0.9,
    fav_def_weakness: 0.7,
    dog_is_hot: false,
    dog_due_goal: true,
    both_no_draw_3: true,
    fav_vulnerability_5: "Elevated",
    fav_cs_streak: 1,
    h2h_dog_gs_last_5: 3,
    dog_venue_wins: 2,
  },
];

// ── Live (engine vocabulary from LIVE_SCANNER stage1–7) ───────────────────────

/** Stage 1 strategic audit — mirrors console Player|Pos|Apps|Mins|Rating|Status board. */
export const MOCK_LIVE_PREMATCH_AUDIT: LivePrematchAudit[] = [
  {
    fixture_id: "18742",
    fixture: "Arsenal vs Liverpool",
    kickoff_utc: "14:00",
    status_text: "LIVE",
    odds_home_win: 2.1,
    odds_away_win: 3.4,
    odds_o25: 1.72,
    combined_miss: 5,
    home: {
      team_id: "19",
      team_name: "Arsenal",
      loc: "home",
      miss: 2,
      kmv: 28.4,
      rv: 33.1,
      gk_out: false,
      gk_status: "Solid Form (0.9 per 90)",
      def_miss: 1,
      mid_miss: 1,
      att_miss: 0,
      l_wing_miss: false,
      r_wing_miss: false,
      players: [
        { name: "David Raya", pos: "Goalkeeper", apps: 28, mins: 2520, rating: 6.92, status: "Solid Form (0.9 per 90)" },
        { name: "William Saliba", pos: "Defender", apps: 30, mins: 2700, rating: 7.21, status: "STARTING" },
        { name: "Gabriel Magalhaes", pos: "Defender", apps: 29, mins: 2610, rating: 7.05, status: "STARTING" },
        { name: "Jurrien Timber", pos: "Defender", apps: 18, mins: 1400, rating: 6.7, status: "MISSING !!!" },
        { name: "Oleksandr Zinchenko", pos: "Defender", apps: 16, mins: 1200, rating: 6.55, status: "STARTING" },
        { name: "Declan Rice", pos: "Midfielder", apps: 29, mins: 2550, rating: 7.4, status: "STARTING" },
        { name: "Martin Odegaard", pos: "Midfielder", apps: 22, mins: 1800, rating: 7.1, status: "MISSING !!!" },
        { name: "Thomas Partey", pos: "Midfielder", apps: 20, mins: 1600, rating: 6.85, status: "STARTING" },
        { name: "Bukayo Saka", pos: "Attacker", apps: 27, mins: 2300, rating: 7.55, status: "STARTING" },
        { name: "Kai Havertz", pos: "Attacker", apps: 26, mins: 2200, rating: 6.95, status: "STARTING" },
        { name: "Gabriel Martinelli", pos: "Attacker", apps: 24, mins: 1900, rating: 7.0, status: "STARTING" },
      ],
    },
    away: {
      team_id: "14",
      team_name: "Liverpool",
      loc: "away",
      miss: 3,
      kmv: 41.8,
      rv: 48.2,
      gk_out: true,
      gk_status: "Proven Liability (1.8 per 90)",
      def_miss: 1,
      mid_miss: 1,
      att_miss: 1,
      l_wing_miss: true,
      r_wing_miss: false,
      players: [
        { name: "Alisson Becker", pos: "Goalkeeper", apps: 20, mins: 1800, rating: 6.4, status: "MISSING (Proven Liability (1.8 per 90))" },
        { name: "Virgil van Dijk", pos: "Defender", apps: 28, mins: 2520, rating: 7.3, status: "STARTING" },
        { name: "Ibrahima Konate", pos: "Defender", apps: 16, mins: 1200, rating: 6.8, status: "MISSING !!!" },
        { name: "Andrew Robertson", pos: "Defender", apps: 25, mins: 2100, rating: 6.9, status: "STARTING" },
        { name: "Trent Alexander-Arnold", pos: "Defender", apps: 27, mins: 2300, rating: 7.15, status: "STARTING" },
        { name: "Alexis Mac Allister", pos: "Midfielder", apps: 24, mins: 2000, rating: 7.0, status: "MISSING !!!" },
        { name: "Dominik Szoboszlai", pos: "Midfielder", apps: 22, mins: 1800, rating: 6.95, status: "STARTING" },
        { name: "Ryan Gravenberch", pos: "Midfielder", apps: 21, mins: 1700, rating: 6.8, status: "STARTING" },
        { name: "Luis Diaz", pos: "Attacker", apps: 25, mins: 2100, rating: 7.2, status: "MISSING !!!" },
        { name: "Mohamed Salah", pos: "Attacker", apps: 30, mins: 2650, rating: 7.6, status: "STARTING" },
        { name: "Darwin Nunez", pos: "Attacker", apps: 23, mins: 1600, rating: 6.7, status: "STARTING" },
      ],
    },
    picks: [
      { type: "TO_SCORE", target_loc: "home" },
      { type: "GG" },
      "BROKEN SHIELD: OVER 2.5 GOALS",
    ],
    killer_rules: ["BROKEN SHIELD: OVER 2.5 GOALS"],
  },
  {
    fixture_id: "18755",
    fixture: "Inter vs Napoli",
    kickoff_utc: "15:30",
    status_text: "Starts in 38m",
    odds_home_win: 1.55,
    odds_away_win: 5.8,
    odds_o25: 1.85,
    combined_miss: 7,
    home: {
      team_id: "108",
      team_name: "Inter",
      loc: "home",
      miss: 1,
      kmv: 12.0,
      rv: 14.5,
      gk_out: false,
      gk_status: "Solid Form (0.7 per 90)",
      def_miss: 0,
      mid_miss: 1,
      att_miss: 0,
      l_wing_miss: false,
      r_wing_miss: false,
      players: [
        { name: "Yann Sommer", pos: "Goalkeeper", apps: 30, mins: 2700, rating: 7.0, status: "Solid Form (0.7 per 90)" },
        { name: "Alessandro Bastoni", pos: "Defender", apps: 28, mins: 2500, rating: 7.1, status: "STARTING" },
        { name: "Francesco Acerbi", pos: "Defender", apps: 26, mins: 2300, rating: 6.9, status: "STARTING" },
        { name: "Benjamin Pavard", pos: "Defender", apps: 22, mins: 1800, rating: 6.85, status: "STARTING" },
        { name: "Federico Dimarco", pos: "Defender", apps: 24, mins: 2000, rating: 7.05, status: "STARTING" },
        { name: "Nicolò Barella", pos: "Midfielder", apps: 20, mins: 1600, rating: 7.1, status: "MISSING !!!" },
        { name: "Hakan Calhanoglu", pos: "Midfielder", apps: 27, mins: 2400, rating: 7.2, status: "STARTING" },
        { name: "Henrikh Mkhitaryan", pos: "Midfielder", apps: 25, mins: 2000, rating: 6.8, status: "STARTING" },
        { name: "Lautaro Martinez", pos: "Attacker", apps: 28, mins: 2400, rating: 7.5, status: "STARTING" },
        { name: "Marcus Thuram", pos: "Attacker", apps: 26, mins: 2100, rating: 7.15, status: "STARTING" },
        { name: "Davide Frattesi", pos: "Midfielder", apps: 18, mins: 1400, rating: 6.9, status: "STARTING" },
      ],
    },
    away: {
      team_id: "113",
      team_name: "Napoli",
      loc: "away",
      miss: 6,
      kmv: 62.4,
      rv: 71.0,
      gk_out: true,
      gk_status: "Small Sample Leak (1.5 per 90)",
      def_miss: 2,
      mid_miss: 2,
      att_miss: 2,
      l_wing_miss: true,
      r_wing_miss: true,
      players: [
        { name: "Alex Meret", pos: "Goalkeeper", apps: 12, mins: 900, rating: 6.2, status: "MISSING (Small Sample Leak (1.5 per 90))" },
        { name: "Giovanni Di Lorenzo", pos: "Defender", apps: 26, mins: 2300, rating: 6.9, status: "MISSING !!!" },
        { name: "Amir Rrahmani", pos: "Defender", apps: 24, mins: 2100, rating: 6.75, status: "MISSING !!!" },
        { name: "Mathias Olivera", pos: "Defender", apps: 20, mins: 1600, rating: 6.6, status: "STARTING" },
        { name: "Stanislav Lobotka", pos: "Midfielder", apps: 24, mins: 2100, rating: 7.0, status: "MISSING !!!" },
        { name: "Andre Zambo Anguissa", pos: "Midfielder", apps: 22, mins: 1800, rating: 6.85, status: "MISSING !!!" },
        { name: "Billy Gilmour", pos: "Midfielder", apps: 18, mins: 1400, rating: 6.7, status: "STARTING" },
        { name: "Khvicha Kvaratskhelia", pos: "Attacker", apps: 22, mins: 1800, rating: 7.4, status: "MISSING !!!" },
        { name: "Victor Osimhen", pos: "Attacker", apps: 18, mins: 1500, rating: 7.3, status: "MISSING !!!" },
        { name: "Giacomo Raspadori", pos: "Attacker", apps: 20, mins: 1400, rating: 6.8, status: "STARTING" },
        { name: "Matteo Politano", pos: "Attacker", apps: 21, mins: 1500, rating: 6.9, status: "STARTING" },
      ],
    },
    picks: [
      { type: "U2.5" },
      { type: "O2.5" },
      { type: "TO_SCORE", target_loc: "home" },
      "FALSE FAVORITE: Napoli TO SCORE/DRAW",
      "TITAN LOCK: Inter -1.5 HANDICAP",
    ],
    killer_rules: [
      "FALSE FAVORITE: Napoli TO SCORE/DRAW",
      "TITAN LOCK: Inter -1.5 HANDICAP",
    ],
  },
  {
    fixture_id: "18761",
    fixture: "Benfica vs Porto",
    kickoff_utc: "18:00",
    status_text: "Starts in 55m",
    odds_home_win: 2.05,
    odds_away_win: 3.5,
    odds_o25: 1.68,
    combined_miss: 4,
    home: {
      team_id: "211",
      team_name: "Benfica",
      loc: "home",
      miss: 2,
      kmv: 24.0,
      rv: 27.5,
      gk_out: true,
      gk_status: "Proven Liability (1.6 per 90)",
      def_miss: 1,
      mid_miss: 1,
      att_miss: 0,
      l_wing_miss: false,
      r_wing_miss: false,
      players: [
        { name: "Anatoliy Trubin", pos: "Goalkeeper", apps: 22, mins: 1980, rating: 6.35, status: "MISSING (Proven Liability (1.6 per 90))" },
        { name: "Antonio Silva", pos: "Defender", apps: 26, mins: 2300, rating: 6.95, status: "STARTING" },
        { name: "Nicolas Otamendi", pos: "Defender", apps: 28, mins: 2500, rating: 7.0, status: "STARTING" },
        { name: "Alexander Bah", pos: "Defender", apps: 18, mins: 1400, rating: 6.6, status: "MISSING !!!" },
        { name: "Fredrik Aursnes", pos: "Midfielder", apps: 25, mins: 2100, rating: 6.9, status: "MISSING !!!" },
        { name: "Orkun Kokcu", pos: "Midfielder", apps: 24, mins: 2000, rating: 6.85, status: "STARTING" },
        { name: "Florentino Luis", pos: "Midfielder", apps: 20, mins: 1600, rating: 6.7, status: "STARTING" },
        { name: "Angel Di Maria", pos: "Attacker", apps: 20, mins: 1500, rating: 7.2, status: "STARTING" },
        { name: "Vangelis Pavlidis", pos: "Attacker", apps: 22, mins: 1800, rating: 7.05, status: "STARTING" },
        { name: "Kerem Akturkoglu", pos: "Attacker", apps: 19, mins: 1500, rating: 6.9, status: "STARTING" },
        { name: "Arthur Cabral", pos: "Attacker", apps: 15, mins: 900, rating: 6.5, status: "STARTING" },
      ],
    },
    away: {
      team_id: "212",
      team_name: "Porto",
      loc: "away",
      miss: 2,
      kmv: 22.5,
      rv: 26.0,
      gk_out: true,
      gk_status: "NO DATA (High Risk)",
      def_miss: 0,
      mid_miss: 1,
      att_miss: 1,
      l_wing_miss: false,
      r_wing_miss: true,
      players: [
        { name: "Diogo Costa", pos: "Goalkeeper", apps: 8, mins: 720, rating: 6.1, status: "MISSING (NO DATA (High Risk))" },
        { name: "Pepe", pos: "Defender", apps: 20, mins: 1700, rating: 6.8, status: "STARTING" },
        { name: "Otavio Ataide", pos: "Defender", apps: 22, mins: 1900, rating: 6.75, status: "STARTING" },
        { name: "Joao Mario", pos: "Defender", apps: 18, mins: 1400, rating: 6.6, status: "STARTING" },
        { name: "Alan Varela", pos: "Midfielder", apps: 21, mins: 1800, rating: 6.85, status: "MISSING !!!" },
        { name: "Stephen Eustaquio", pos: "Midfielder", apps: 19, mins: 1500, rating: 6.7, status: "STARTING" },
        { name: "Pepê", pos: "Attacker", apps: 24, mins: 1900, rating: 6.95, status: "MISSING !!!" },
        { name: "Galeno", pos: "Attacker", apps: 26, mins: 2200, rating: 7.1, status: "STARTING" },
        { name: "Evanilson", pos: "Attacker", apps: 23, mins: 1900, rating: 7.0, status: "STARTING" },
        { name: "Francisco Conceicao", pos: "Attacker", apps: 20, mins: 1500, rating: 6.9, status: "STARTING" },
        { name: "Wendell", pos: "Defender", apps: 17, mins: 1300, rating: 6.55, status: "STARTING" },
      ],
    },
    picks: [
      { type: "TO_SCORE", target_loc: "home" },
      { type: "TO_SCORE", target_loc: "away" },
      { type: "GG" },
      "BROKEN SHIELD: OVER 2.5 GOALS",
    ],
    killer_rules: ["BROKEN SHIELD: OVER 2.5 GOALS"],
  },
];

/** Thin feed kept for any legacy consumers. */
export const MOCK_LIVE_PREMATCH: LivePrematchPick[] = MOCK_LIVE_PREMATCH_AUDIT.map((fx) => ({
  fixture_id: fx.fixture_id,
  picks: fx.picks
    .filter((p): p is { type: string; target_loc?: string } => typeof p === "object")
    .map((p) => ({ type: p.type, target_loc: p.target_loc })),
}));

/** Stage 2 VALIDATED_ALERTS rows — supreme alerts after 45' confirmation. */
export const MOCK_LIVE_VALIDATION_ALERTS: LiveValidationPick[] = [
  {
    fixture_id: "18742",
    match_name: "Arsenal vs Liverpool",
    prediction_type: "GG",
    target: "match",
    forensic_note: "EXPLOITED (Opponent utilizing structural gap)",
    stats_note: "STATS_3/3",
    minute_triggered: 47,
    scores: "1-1",
    timestamp: "2026-07-28T14:12:08",
  },
  {
    fixture_id: "18742",
    match_name: "Arsenal vs Liverpool",
    prediction_type: "TO_SCORE",
    target: "home",
    forensic_note: "WEAKENED (Substitution impact detected)",
    stats_note: "STATS_2/3",
    minute_triggered: 52,
    scores: "1-1",
    timestamp: "2026-07-28T14:18:41",
  },
  {
    fixture_id: "18755",
    match_name: "Inter vs Napoli",
    prediction_type: "TO_SCORE",
    target: "home",
    forensic_note: "MAINTAINED (No structural fracture detected)",
    stats_note: "STATS_3/3",
    minute_triggered: 49,
    scores: "2-0",
    timestamp: "2026-07-28T14:05:22",
  },
  {
    fixture_id: "18761",
    match_name: "Benfica vs Porto",
    prediction_type: "OVER_2.5",
    target: "match",
    forensic_note: "EXPLOITED (Opponent utilizing structural gap)",
    stats_note: "STATS_3/3",
    minute_triggered: 61,
    scores: "2-1",
    timestamp: "2026-07-28T14:33:09",
  },
];

/**
 * Stage 2 VALIDATION BOARD — mirrors print_cycle_board.
 * Tracks stage 1 picks: monitoring → 30' handshake → 45' supreme → settled.
 */
export const MOCK_LIVE_VALIDATION: LiveValidationBoard = {
  cycle: 14,
  total_live: 18,
  total_tracked: 3,
  matches: [
    {
      name: "Arsenal vs Liverpool",
      minute: 52,
      id: "18742",
      score: "1-1",
      lines: [
        "   🔥 [GG] SUPREME ALERT FIRED @ 47'",
        "   🔥 [TO_SCORE (home)] SUPREME ALERT FIRED @ 52'",
        "   👁️  [BROKEN SHIELD: OVER 2.5 GOALS] Monitoring @ 52' | Forensic ❌ | Stats ✅",
      ],
    },
    {
      name: "Inter vs Napoli",
      minute: 49,
      id: "18755",
      score: "2-0",
      lines: [
        "   ✅ [TO_SCORE (home)] SETTLED → Home scored ✅",
        "   🤝 [U2.5] 30' HANDSHAKE PASSED — Saved to state",
        "   ⏳ [O2.5] 45'+ waiting: Forensic ❌ | Stats ✅",
        "   👁️  [FALSE FAVORITE: Napoli TO SCORE/DRAW] Queued for 45' @ 49' | Forensic ✅ | Stats ❌",
      ],
    },
    {
      name: "Benfica vs Porto",
      minute: 61,
      id: "18761",
      score: "2-1",
      lines: [
        "   🔥 [OVER_2.5] SUPREME ALERT FIRED @ 61'",
        "   ⚡ [TO_SCORE (home)] FINAL STRIKE WINDOW @ 61' — Gap still exploited",
        "   💤 [TO_SCORE (away)] Final strike window — gap closed",
        "   ✅ [GG] SETTLED → GG settled ✅",
      ],
    },
  ],
  alerts: MOCK_LIVE_VALIDATION_ALERTS,
};

/** Stage 6 fire_alert rows — VIP + free LIVE orchestrator. */
export const MOCK_LIVE_ALERTS: LiveAlertPick[] = [
  {
    f_id: "18742",
    fixture: "Arsenal vs Liverpool",
    time: "2026-07-28T14:12:08",
    minute: 47,
    level: "🔥 PREMIUM",
    confidence: 72,
    msg: "Arsenal vs Liverpool — 45' Verified. Chaos:8.4 | H-xG:1.42 A-xG:1.55",
    session: "20260728_141000",
  },
  {
    f_id: "18742",
    fixture: "Arsenal vs Liverpool",
    time: "2026-07-28T14:14:02",
    minute: 48,
    level: "🔥 PREMIUM",
    confidence: 72,
    msg: "Pre-match '🔥 BOTH 2H GOAL (100%)' fused with live chaos (8.4) | Conf: 72%",
    session: "20260728_141000",
  },
  {
    f_id: "18755",
    fixture: "Inter vs Napoli",
    time: "2026-07-28T14:05:22",
    minute: 49,
    level: "✅ STANDARD",
    confidence: 58,
    msg: "HOME dominating Pressure Share (67.0%) | xG: 1.81 | SOT: 6 | DA: 42",
    session: "20260728_141000",
  },
  {
    f_id: "18755",
    fixture: "Inter vs Napoli",
    time: "2026-07-28T14:06:10",
    minute: 49,
    level: "✅ STANDARD",
    confidence: 58,
    msg: "Inter vs Napoli — 45' Verified. Chaos:5.2 | H-xG:1.81 A-xG:0.44",
    session: "20260728_141000",
  },
  {
    f_id: "18801",
    fixture: "Sevilla vs Betis",
    time: "2026-07-28T14:21:55",
    minute: 38,
    level: "📊 MONITOR",
    confidence: 41,
    msg: "Live Snapshot | Conf: 41% | H-Pressure: 44.0% | A-Pressure: 56.0% | Chaos: 6.1 | H-xG: 0.9 | A-xG: 1.1",
    session: "20260728_141000",
  },
  {
    f_id: "18761",
    fixture: "Benfica vs Porto",
    time: "2026-07-28T14:33:09",
    minute: 61,
    level: "🔥 PREMIUM",
    confidence: 69,
    msg: "Benfica vs Porto — 45' Verified. Chaos:7.8 | H-xG:1.66 A-xG:1.21",
    session: "20260728_141000",
  },
  {
    f_id: "18761",
    fixture: "Benfica vs Porto",
    time: "2026-07-28T14:34:01",
    minute: 62,
    level: "🔥 PREMIUM",
    confidence: 69,
    msg: "AWAY dominating Pressure Share (52.0%) | xG: 1.21 | SOT: 4 | DA: 31",
    session: "20260728_141000",
  },
];

/** Stage 6 orchestrator board — cycle_matches + nested Code 6 intel/forensics. */
export const MOCK_LIVE_ORCHESTRATOR: LiveOrchestratorBoard = {
  session: "20260728_141000",
  cycle: 12,
  total_live: 4,
  total_db: 3,
  matches: [
    {
      name: "Arsenal vs Liverpool",
      id: "18742",
      minute: 47,
      conf: 72,
      h_pressure: 48.2,
      a_pressure: 51.8,
      chaos: 8.4,
      h_xg: 1.42,
      a_xg: 1.55,
      h_sot: 4,
      a_sot: 5,
      structural: "OK",
      in_db: true,
      validation: "SUPREME_45",
      settled: ["GG", "O2.5"],
      intel: {
        home: { live_xg: 1.42, sot: 4, da: 38 },
        away: { live_xg: 1.55, sot: 5, da: 41 },
        match: {
          confidence_score: 72,
          chaos_index: 8.4,
          h_pressure_share: 48.2,
          a_pressure_share: 51.8,
        },
      },
      forensics: {
        status: "OK",
        h_doom: 1.12,
        a_doom: 1.35,
        h_red: false,
        a_red: false,
        h_gk: false,
        a_gk: true,
        h_triple: false,
        a_triple: false,
      },
      alerts: [
        {
          id: "18742_USER_FUSED",
          tier: "🔥 PREMIUM",
          conf: 72,
          msg: "Pre-match '🔥 BOTH 2H GOAL (100%)' fused with live chaos (8.4) | Conf: 72%",
        },
        {
          id: "18742_SNAPSHOT",
          tier: "📊 MONITOR",
          conf: 55,
          msg: "Live Snapshot | Conf: 55% | H-Pressure: 48.2% | A-Pressure: 51.8% | Chaos: 8.4 | H-xG: 1.42 | A-xG: 1.55",
        },
      ],
    },
    {
      name: "Inter vs Napoli",
      id: "18755",
      minute: 49,
      conf: 58,
      h_pressure: 67.0,
      a_pressure: 33.0,
      chaos: 5.2,
      h_xg: 1.81,
      a_xg: 0.44,
      h_sot: 6,
      a_sot: 1,
      structural: "OK",
      in_db: true,
      validation: "SUPREME_45",
      settled: ["GG"],
      intel: {
        home: { live_xg: 1.81, sot: 6, da: 42 },
        away: { live_xg: 0.44, sot: 1, da: 18 },
        match: {
          confidence_score: 58,
          chaos_index: 5.2,
          h_pressure_share: 67.0,
          a_pressure_share: 33.0,
        },
      },
      forensics: {
        status: "OK",
        h_doom: 0.88,
        a_doom: 1.92,
        h_red: false,
        a_red: true,
        h_gk: false,
        a_gk: false,
        h_triple: false,
        a_triple: true,
      },
      alerts: [
        {
          id: "18755_USER_PRESSURE_HOME",
          tier: "✅ STANDARD",
          conf: 58,
          msg: "HOME dominating Pressure Share (67.0%) | xG: 1.81 | SOT: 6 | DA: 42",
        },
      ],
    },
    {
      name: "Sevilla vs Betis",
      id: "18801",
      minute: 38,
      conf: 41,
      h_pressure: 44.0,
      a_pressure: 56.0,
      chaos: 6.1,
      h_xg: 0.9,
      a_xg: 1.1,
      h_sot: 2,
      a_sot: 3,
      structural: "INSUFFICIENT_SQUAD_DATA",
      in_db: false,
      validation: "VALID_30",
      settled: [],
      intel: {
        home: { live_xg: 0.9, sot: 2, da: 22 },
        away: { live_xg: 1.1, sot: 3, da: 28 },
        match: {
          confidence_score: 41,
          chaos_index: 6.1,
          h_pressure_share: 44.0,
          a_pressure_share: 56.0,
        },
      },
      forensics: {
        status: "INSUFFICIENT_SQUAD_DATA",
        h_doom: 0,
        a_doom: 0,
        h_red: false,
        a_red: false,
        h_gk: false,
        a_gk: false,
      },
      alerts: [
        {
          id: "18801_SNAPSHOT",
          tier: "📊 MONITOR",
          conf: 41,
          msg: "Live Snapshot | Conf: 41% | H-Pressure: 44.0% | A-Pressure: 56.0% | Chaos: 6.1 | H-xG: 0.9 | A-xG: 1.1",
        },
      ],
    },
    {
      name: "Benfica vs Porto",
      id: "18761",
      minute: 61,
      conf: 69,
      h_pressure: 52.0,
      a_pressure: 48.0,
      chaos: 7.8,
      h_xg: 1.66,
      a_xg: 1.21,
      h_sot: 5,
      a_sot: 4,
      structural: "OK",
      in_db: true,
      validation: "SUPREME_45",
      settled: ["O2.5"],
      intel: {
        home: { live_xg: 1.66, sot: 5, da: 35 },
        away: { live_xg: 1.21, sot: 4, da: 31 },
        match: {
          confidence_score: 69,
          chaos_index: 7.8,
          h_pressure_share: 52.0,
          a_pressure_share: 48.0,
        },
      },
      forensics: {
        status: "OK",
        h_doom: 1.05,
        a_doom: 1.1,
        h_red: false,
        a_red: false,
        h_gk: true,
        a_gk: false,
      },
      alerts: [
        {
          id: "18761_USER_FUSED",
          tier: "🔥 PREMIUM",
          conf: 69,
          msg: "Pre-match '🔥 BOTH 2H GOAL (100%)' fused with live chaos (7.8) | Conf: 69%",
        },
        {
          id: "18761_USER_PRESSURE_AWAY",
          tier: "🔥 PREMIUM",
          conf: 69,
          msg: "AWAY dominating Pressure Share (52.0%) | xG: 1.21 | SOT: 4 | DA: 31",
        },
      ],
    },
  ],
};

export const MOCK_LIVE_INCOMING: LiveIncomingPick[] = [
  {
    fixture_id: "18742",
    fixture: "Arsenal vs Liverpool",
    picks: [
      {
        type: "OVER_GG",
        reason: "Both sides 2H pressure spike — DA delta +18 since kickoff",
      },
      {
        type: "TO_SCORE",
        target_loc: "away",
        target_name: "Liverpool",
        reason: "Away spear unlocked after home CB fatigue flag",
      },
      {
        type: "GG_OVER_2.5",
        reason: "Combined lambda climb 2.91 → live GG + O2.5 convergence",
      },
    ],
  },
  {
    fixture_id: "18755",
    fixture: "Inter vs Napoli",
    picks: [
      {
        type: "WIN",
        target_loc: "home",
        target_name: "Inter",
        reason: "Home chokehold intact — Napoli GK leak elevated",
      },
      {
        type: "MONITOR",
        reason: "Away missing 4 key bodies — watch REDLIGHT cascade",
      },
      {
        type: "OVER_2.5",
        reason: "Open style alignment 🔥 — both DA > 35",
      },
    ],
  },
  {
    fixture_id: "18761",
    fixture: "Benfica vs Porto",
    picks: [
      {
        type: "GG",
        reason: "H2H BTTS venue 4/5 — midfield friction collapsing",
      },
      {
        type: "WIN_DRAW",
        target_loc: "home",
        target_name: "Benfica",
        reason: "Double-chance lean while Porto SH threat monitored",
      },
    ],
  },
];

export const MOCK_LIVE_DASHBOARD: LiveDashboardResult[] = [
  {
    fixture: "Arsenal vs Liverpool",
    fixture_id: "18742",
    Win: {
      base: 54,
      adj: 71,
      pick: "Away",
      light: "🟢 GREENLIGHT (Elite)",
      reason: "Away form + home CB absences — adj capped after danger sync",
    },
    GG: {
      base: 68,
      adj: 82,
      light: "🟢 GREENLIGHT (Elite)",
      reason: "Both keepers liable; live pressure confirms morning GG head",
    },
    O25: {
      base: 61,
      adj: 74,
      light: "🟡 PLAYABLE (Caution)",
      reason: "Council lean live — watch 60' under trap",
    },
    Corner: {
      base: 58,
      adj: 66,
      light: "🟡 PLAYABLE (Caution)",
      reason: "Wounded-beast away wing — corner tier climbing",
    },
    SH_GG: {
      base: 72,
      adj: 85,
      light: "🟢 GREENLIGHT (Elite)",
      reason: "SH pressure 78 — late threat HIGH both sides",
    },
  },
  {
    fixture: "Inter vs Napoli",
    fixture_id: "18755",
    Win: {
      base: 66,
      adj: 79,
      pick: "Home",
      light: "🟢 GREENLIGHT (Elite)",
      reason: "Napoli breach — Inter win path clear",
    },
    GG: {
      base: 48,
      adj: 41,
      light: "🛑 REDLIGHT (Veto/Danger)",
      reason: "Away attack stripped — GG veto while breach active",
    },
    O25: {
      base: 52,
      adj: 44,
      light: "🛑 REDLIGHT (Veto/Danger)",
      reason: "Under bias after Napoli spear collapse",
    },
    Corner: {
      base: 55,
      adj: 63,
      light: "🟡 PLAYABLE (Caution)",
      reason: "Home corner pressure only — one-way flow",
    },
    SH_GG: {
      base: 40,
      adj: 28,
      light: "🛑 REDLIGHT (Veto/Danger)",
      reason: "SH GG killed — away missing front three",
    },
  },
  {
    fixture: "Benfica vs Porto",
    fixture_id: "18761",
    Win: {
      base: 49,
      adj: 52,
      pick: "Home",
      light: "🟡 PLAYABLE (Caution)",
      reason: "Parity gap thin — no chokehold yet",
    },
    GG: {
      base: 64,
      adj: 70,
      light: "🟡 PLAYABLE (Caution)",
      reason: "H2H GG strong; live tempo still settling",
    },
    O25: {
      base: 57,
      adj: 61,
      light: "🟡 PLAYABLE (Caution)",
      reason: "Borderline — wait for 2H script",
    },
    Corner: {
      base: 62,
      adj: 68,
      light: "🟢 GREENLIGHT (Elite)",
      reason: "Both persistent venue corner sides",
    },
    SH_GG: {
      base: 0,
      adj: 0,
      light: "⚪ N/A",
      reason: "SH head not armed for this fixture",
    },
  },
];

export const MOCK_LIVE_DANGER: LiveDangerReport[] = [
  {
    fixture: "Arsenal vs Liverpool",
    fixture_id: "18742",
    home_team: {
      team_name: "Arsenal",
      id: 19,
      breach: false,
      danger_level: "✅ SAFE",
      vulnerability_pct: 28,
      gk_leak: 0.95,
      missing_details: [{ name: "Timber", pos: "D" }],
      formation: "4-3-3",
      style: { label: "Attacking", score: 78, da: 52 },
    },
    away_team: {
      team_name: "Liverpool",
      id: 14,
      breach: false,
      danger_level: "✅ SAFE",
      vulnerability_pct: 34,
      gk_leak: 1.05,
      missing_details: [],
      formation: "4-3-3",
      style: { label: "Attacking", score: 81, da: 58 },
    },
    style_alignment: "🔥 OPEN",
    match_chemistry_list: {
      Gg: "Elite",
      Corner: "Very Strong",
      "Home Win": "Strong",
      "Away Win": "Excellent",
      "Over2.5": "Excellent",
      "Under3.5": "Weak",
      "Over1.5": "Elite",
    },
  },
  {
    fixture: "Inter vs Napoli",
    fixture_id: "18755",
    home_team: {
      team_name: "Inter",
      id: 108,
      breach: false,
      danger_level: "✅ SAFE",
      vulnerability_pct: 18,
      gk_leak: 0.72,
      missing_details: [],
      formation: "3-5-2",
      style: { label: "Balanced", score: 74, da: 41 },
    },
    away_team: {
      team_name: "Napoli",
      id: 113,
      breach: true,
      danger_level: "🔴 DANGER",
      vulnerability_pct: 76,
      gk_leak: 1.55,
      missing_details: [
        { name: "Osimhen", pos: "F" },
        { name: "Kvaratskhelia", pos: "F" },
        { name: "Lobotka", pos: "M" },
        { name: "Di Lorenzo", pos: "D" },
      ],
      formation: "4-3-3",
      style: { label: "Defensive", score: 44, da: 22 },
    },
    style_alignment: "⚠️ TIGHT",
    match_chemistry_list: {
      Gg: "Very Weak",
      Corner: "Strong",
      "Home Win": "Elite",
      "Away Win": "Very Weak",
      "Over2.5": "Weak",
      "Under3.5": "Excellent",
      "Over1.5": "Strong",
    },
  },
  {
    fixture: "Benfica vs Porto",
    fixture_id: "18761",
    home_team: {
      team_name: "Benfica",
      id: 211,
      breach: false,
      danger_level: "✅ SAFE",
      vulnerability_pct: 31,
      gk_leak: 1.1,
      missing_details: [{ name: "Aursnes", pos: "M" }],
      formation: "4-2-3-1",
      style: { label: "Attacking", score: 69, da: 47 },
    },
    away_team: {
      team_name: "Porto",
      id: 212,
      breach: false,
      danger_level: "✅ SAFE",
      vulnerability_pct: 29,
      gk_leak: 1.0,
      missing_details: [],
      formation: "4-4-2",
      style: { label: "Balanced", score: 66, da: 39 },
    },
    style_alignment: "🔥 OPEN",
    match_chemistry_list: {
      Gg: "Very Strong",
      Corner: "Elite",
      "Home Win": "Strong",
      "Away Win": "Strong",
      "Over2.5": "Strong",
      "Under3.5": "Weak",
      "Over1.5": "Excellent",
    },
  },
];

export const MOCK_LIVE_AGG: LiveAggregatorReport[] = [
  {
    fixture: "Arsenal vs Liverpool",
    fixture_id: "18742",
    incoming_probabilities: [
      { type: "OVER_GG", reason: "Both sides 2H pressure spike" },
      { type: "TO_SCORE", target_loc: "away", target_name: "Liverpool" },
      { type: "GG_OVER_2.5", reason: "Lambda climb live" },
    ],
    danger_report: {
      home: { status: "✅ SAFE", sync: "ELITE", breach: false },
      away: { status: "✅ SAFE", sync: "STABLE", breach: false },
    },
    match_chemistry_list: {
      Gg: "Elite",
      Corner: "Very Strong",
      "Home Win": "Strong",
      "Away Win": "Excellent",
      "Over2.5": "Excellent",
      "Under3.5": "Weak",
      "Over1.5": "Elite",
    },
  },
  {
    fixture: "Inter vs Napoli",
    fixture_id: "18755",
    incoming_probabilities: [
      { type: "WIN", target_loc: "home", target_name: "Inter" },
      { type: "MONITOR", reason: "Away breach cascade" },
    ],
    danger_report: {
      home: { status: "✅ SAFE", sync: "STABLE", breach: false },
      away: { status: "🔴 DANGER", sync: "CONFLICT", breach: true },
    },
    match_chemistry_list: {
      Gg: "Very Weak",
      Corner: "Strong",
      "Home Win": "Elite",
      "Away Win": "Very Weak",
      "Over2.5": "Weak",
      "Under3.5": "Excellent",
      "Over1.5": "Strong",
    },
  },
  {
    fixture: "Benfica vs Porto",
    fixture_id: "18761",
    incoming_probabilities: [
      { type: "GG", reason: "H2H BTTS venue" },
      { type: "WIN_DRAW", target_loc: "home", target_name: "Benfica" },
    ],
    danger_report: {
      home: { status: "✅ SAFE", sync: "STABLE", breach: false },
      away: { status: "✅ SAFE", sync: "ELITE", breach: false },
    },
    match_chemistry_list: {
      Gg: "Very Strong",
      Corner: "Elite",
      "Home Win": "Strong",
      "Away Win": "Strong",
      "Over2.5": "Strong",
      "Under3.5": "Weak",
      "Over1.5": "Excellent",
    },
  },
];

/** Generic weekly filter demo rows (DynamicTable). */
export const MOCK_FILTER_ROWS: Record<string, unknown>[] = [
  {
    fixture: "Man City vs Arsenal",
    market: "GG",
    tier: "Category 1",
    prob: 78.4,
    odds: 1.72,
    note: "Demo — API offline",
  },
  {
    fixture: "Real Madrid vs Alaves",
    market: "Win",
    tier: "Category 1",
    prob: 81.6,
    odds: 1.35,
    note: "Demo — API offline",
  },
];
